multisensor_sensors:
  ros__parameters:
    publish_rate: 10.0
    frame_id: "camera_link"
    qos.reliability: "best_effort"
    qos.history: "keep_last"
    qos.depth: 10
    image_width: 320
    image_height: 240
    image_rate: 10.0
    points_per_scan: 360

